### ISSUE TITLE
Pytorch Lightning version issue

### ISSUE THREAD

**Issue by MAlberts99** [GT4SD/gt4sd-trainer-hf-pl#3]
When installing using python=3.9, Pytorch lightning 2.0.2 get's installed. When running `gt4sd-trainer-hf-pl` this yields:

```
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/nmr/bin/gt4sd-trainer-hf-pl", line 8, in <module>
    sys.exit(main())
  File "/Users/arv/Projects/nmr/gt4sd-trainer-hf-pl/src/gt4sd_trainer/hf_pl/cli_trainer.py", line 167, in main
    pipeline.train(**config)
  File "/Users/arv/Projects/nmr/gt4sd-trainer-hf-pl/src/gt4sd_trainer/hf_pl/pytorch_lightning_trainer.py", line 95, in train
    trainer = Trainer(**pl_trainer_args)
  File "/opt/homebrew/anaconda3/envs/nmr/lib/python3.9/site-packages/pytorch_lightning/utilities/argparse.py", line 69, in insert_env_defaults
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'resume_from_checkpoint'
```

Pytorch Lightning version 1.5.10 to 1.9.5 works without issues. The error only pops up from version 2.0.0

**Comment by christofid** [comment]
Hey @MAlberts99, thanks for letting us know. This issue should have been resolved by #4
